### ISSUE TITLE
is there anybody knows how to convert to onnx file

### ISSUE THREAD

**Issue by qslia** [Epiphqny/VisTR#24]
I cant do it, it output

for i in range(frame_masks.size(1)):
Traceback (most recent call last):
  File "inference.py", line 250, in <module>
    main(args)
  File "inference.py", line 208, in main
    torch.onnx.export(model, img.squeeze(0), "vistr.onnx", export_params=True,verbose=True,opset_version=11, do_constant_folding=True, 
  File "/root/anaconda3/lib/python3.8/site-packages/torch/onnx/__init__.py", line 203, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/root/anaconda3/lib/python3.8/site-packages/torch/onnx/utils.py", line 86, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/root/anaconda3/lib/python3.8/site-packages/torch/onnx/utils.py", line 526, in _export
    graph, params_dict, torch_out = _model_to_graph(model, args, verbose, input_names,
  File "/root/anaconda3/lib/python3.8/site-packages/torch/onnx/utils.py", line 382, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type,
  File "/root/anaconda3/lib/python3.8/site-packages/torch/onnx/utils.py", line 188, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/root/anaconda3/lib/python3.8/site-packages/torch/onnx/__init__.py", line 241, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/root/anaconda3/lib/python3.8/site-packages/torch/onnx/utils.py", line 791, in _run_symbolic_function
    return symbolic_fn(g, *inputs, **attrs)
  File "/root/anaconda3/lib/python3.8/site-packages/torch/onnx/symbolic_helper.py", line 129, in wrapper
    return fn(g, *args)
  File "/root/anaconda3/lib/python3.8/site-packages/torch/onnx/symbolic_opset11.py", line 672, in flatten
    output_dims[start_dim] = output_dims[start_dim] * input_dims[i]
IndexError: list index out of range

**Comment by qslia** [comment]
outputs = model(img)
            torch.onnx.export(model, img.squeeze(0), "vistr.onnx", export_params=True,verbose=True,opset_version=11, do_constant_folding=True,
                    keep_initializers_as_inputs=True)

**Comment by EricWiener** [comment]
@qslia were you able to figure this out?
