### ISSUE TITLE
python inference.py --masks --model_path /home/zhangsai/vistr/vistr_r50.pth

### ISSUE THREAD

**Issue by qzsrh** [Epiphqny/VisTR#61]
When I run this command, :python inference.py --masks --model_path /home/zhangsai/vistr/vistr_r50.pth
the following error occurs：
Process video:  292
Process video:  293
Traceback (most recent call last):
  File "inference.py", line 236, in <module>
    main(args)
  File "inference.py", line 217, in main
    if pred_scores[n,m]<0.001:
IndexError: index 36 is out of bounds for axis 0 with size 36
My dataset is YoutubeVIS，The data format is the same as that of preparation. The Val dataset is used to execute this line of command.
Hope to get your reply, thank you very much!

**Comment by XiangTodayEatsWhat** [comment]
Hello! Have you addressed it? I met the same problem.

**Comment by qzsrh** [comment]
> Hello! Have you addressed it? I met the same problem.

Some of the videos in the test set exceed 36 frames. Just find them and remove them

**Comment by XiangTodayEatsWhat** [comment]
> > Hello! Have you addressed it? I met the same problem.
> 
> Some of the videos in the test set exceed 36 frames. Just find them and remove them

Thank you! It works now!

**Comment by qzsrh** [comment]
> > > Hello! Have you addressed it? I met the same problem.
> > 
> > 
> > Some of the videos in the test set exceed 36 frames. Just find them and remove them
> 
> Thank you! It works now!

However, it seems that there are errors in the json file after my test. I didn't successfully visualize it. If you can successfully visualize it later, please tell me what you did. Thank you very much!

**Comment by shuangkouyizu** [comment]
Have you solved it？
