### ISSUE TITLE
No module named 'pycocotools.ytvos'

### ISSUE THREAD

**Issue by venje-zhu** [Epiphqny/VisTR#68]
I tried to run inference.py and I have configured the required environment according to the requirements in the README, but the following exception occurred:
`(pytorch1.10) root@localhost:/code/video_instance_segmentation/VisTR-master# python inference.py --masks --model_path ./coco_pretrained_weights/ --save_path .
Traceback (most recent call last):
  File "/code/video_instance_segmentation/VisTR-master/inference.py", line 16, in <module>
    import datasets
  File "/code/video_instance_segmentation/VisTR-master/datasets/__init__.py", line 5, in <module>
    from .ytvos import build as build_ytvos
  File "/code/video_instance_segmentation/VisTR-master/datasets/ytvos.py", line 9, in <module>
    from pycocotools.ytvos import YTVOS
ModuleNotFoundError: No module named 'pycocotools.ytvos'`
Why does this kind of problem still occur?
My environment configuration is: pytorch1.10, cuda10.1

**Comment by hans0809** [comment]
你好，请问这个问题解决了吗
